openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Follow search'
  license:
    name: 'GNU General Public License v3.0'
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'

tags:
  - name: 'Migrate'
    description: Data migration
  - name: 'Searches'
    description: Searches handling
security:
  - BearerAuth: []
paths:
  /searches/{searchesId}:
    get:
      operationId: getSearches
      tags:
        - Search
      description: 'Get list of searches.'
      parameters:
        - $ref: '#/components/parameters/searchesId'
      responses:
        200:
          description: 'The list of searches is returned.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Searches'
        404:
          description: 'Unknown list.'
        default:
          description: 'Unspecified error.'

  /searches:
    post:
      operationId: addSearch
      tags:
        - Search
      description: 'Add search to the list.'
      parameters:
        - $ref: '#/components/parameters/searchesIdPost'
        - $ref: '#/components/parameters/searchIdPost'
      responses:
        201:
          description: 'The search was successfully added to the list.'
        404:
          description: 'Unknown search list.'
        default:
          description: 'Unspecified error.'

  /searches/{searchesId}/{searchId}:
    get:
      operationId: checkListMaterial
      tags:
        - List
      description: 'Get the search results for a specific search.'
      parameters:
        - $ref: '#/components/parameters/searchesId'
        - $ref: '#/components/parameters/searchId'
      responses:
        200:
          description: 'The search results.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        404:
          description: 'The search list or search does not exist.'
        default:
          description: 'Unspecified error.'
    delete:
      operationId: deleteSearch
      tags:
        - Search
      description: 'Delete search from list.'
      parameters:
        - $ref: '#/components/parameters/searchesId'
        - $ref: '#/components/parameters/searchId'
      responses:
        204:
          description: 'Successfully removed.'
        404:
          description: 'Unknown search list or search.'
        default:
          description: 'Unspecified error.'
  /migrate/{legacyUserId}:
    put:
      operationId: migrateList
      tags:
        - Migrate
      description: 'Migrate searches for the legacy user identifier to current user.'
      parameters:
        - $ref: '#/components/parameters/legacyUserId'
      responses:
        204:
          description: 'Successfully migrated.'
        default:
          description: 'Unspecified error.'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  parameters:
    searchesId:
      name: 'searchesId'
      in: 'path'
      description: 'The identifier of the searches list to return. Use "default" for the default list.'
      required: true
      example: 'default'
      schema:
        $ref: '#/components/schemas/SearchesId'
    searchId:
      name: 'searchId'
      in: 'path'
      description: 'The identifier of the search.'
      required: true
      example: 'harry potter'
      schema:
        $ref: '#/components/schemas/SearchId'
    searchesIdPost:
      name: 'searchesId'
      in: 'query'
      description: 'The identifier of the searches list to return. Use "default" for the default list.'
      required: true
      example: 'default'
      schema:
        $ref: '#/components/schemas/SearchesId'
    searchIdPost:
      name: 'searchId'
      in: 'query'
      description: 'The identifier of the search.'
      required: true
      example: 'harry potter'
      schema:
        $ref: '#/components/schemas/SearchId'
    legacyUserId:
      name: 'legacyUserId'
      in: 'path'
      description: 'Legacy user identifier of a migrated search.'
      required: true
      example: '29A10F616FE6CA5C6E06EBF507A9FDC5BB89F8EBCF65726BEAC61C646854E83856D3B1D46BE4696EDCFB3C9F57EEBB6941D8654BC1F4B514D6217141AEA1653C'
      schema:
        $ref: '#/components/schemas/LegacyUserId'

  schemas:
    SearchesId:
      description: 'Searches list identifier. In the initial version, this can only be "default".'
      type: string
    SearchId:
      description: 'A search string.'
      type: string
    Searches:
      type: array
      items:
        $ref: '#/components/schemas/SearchInformation'
    SearchResult:
      type: object
      additionalProperties: false
      required:
        - materials
      properties:
        materials:
          $ref: '#/components/schemas/Material'
    SearchQuery:
      type: string
    SearchInformation:
      description: 'Information about search'
      type: object
      additionalProperties:
        false
      properties:
        search:
          $ref: '#/components/schemas/SearchQuery'
        new_count:
          type: integer
    Material:
      description: 'A material'
      type: object
      required:
        - pid
      additionalProperties: true
      properties:
        pid:
          type: string
    LegacyUserId:
      description: 'Legacy user identifier.'
      type: string
      example: '29A10F616FE6CA5C6E06EBF507A9FDC5BB89F8EBCF65726BEAC61C646854E83856D3B1D46BE4696EDCFB3C9F57EEBB6941D8654BC1F4B514D6217141AEA1653C'
