openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Follow search'
  license:
    name: 'GNU General Public License v3.0'
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'

tags:
  - name: 'Search'
  - name: 'Migrate'
    description: Data migration
security:
  - BearerAuth: []
paths:
  /list/{listName}:
    get:
      operationId: getSearches
      tags:
        - Search
      description: 'Get all the users searches.'
      parameters:
        - $ref: '#/components/parameters/listName'
      responses:
        200:
          description: 'The search data is returned.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Searches'
        default:
          description: 'Unspecified error.'

  /list/{listName}/{searchTitle}:
    get:
      operationId: checkListMaterial
      tags:
        - Search
      description: 'Get the search results for a specific search.'
      parameters:
        - $ref: '#/components/parameters/listName'
        - $ref: '#/components/parameters/searchTitle'
      responses:
        200:
          description: 'The search with the specified ID exists.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResult'
        404:
          description: 'The search does not exist.'
        default:
          description: 'Unspecified error.'
    post:
      operationId: addSearch
      tags:
        - Search
      description: 'Add search to the list.'
      requestBody:
        $ref: '#/components/requestBodies/query'
      parameters:
        - $ref: '#/components/parameters/listName'
        - $ref: '#/components/parameters/searchTitle'
      responses:
        201:
          description: 'The search was successfully added to the list.'
        default:
          description: 'Unspecified error.'
    delete:
      operationId: deleteSearch
      tags:
        - Search
      description: 'Delete search from list.'
      parameters:
        - $ref: '#/components/parameters/listName'
        - $ref: '#/components/parameters/searchTitle'
      responses:
        204:
          description: 'Successfully removed.'
        404:
          description: 'Unknown search.'
        default:
          description: 'Unspecified error.'
  /migrate/{legacyUserId}:
    put:
      operationId: migrateList
      tags:
        - Migrate
      description: 'Migrate searches for the legacy user identifier to current user.'
      parameters:
        - $ref: '#/components/parameters/legacyUserId'
      responses:
        204:
          description: 'Successfully migrated.'
        default:
          description: 'Unspecified error.'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  parameters:
    listName:
      name: 'listName'
      in: 'path'
      description: 'The name of the list containing searches.'
      required: true
      example: 'Fiction'
      schema:
        $ref: '#/components/schemas/Query'
    searchTitle:
      name: 'searchTitle'
      in: 'path'
      description: 'The title of the search to remove.'
      required: true
      example: 'Harry Potter'
      schema:
        $ref: '#/components/schemas/Query'
    legacyUserId:
      name: 'legacyUserId'
      in: 'path'
      description: 'Legacy user identifier of a migrated search.'
      required: true
      example: '29A10F616FE6CA5C6E06EBF507A9FDC5BB89F8EBCF65726BEAC61C646854E83856D3B1D46BE4696EDCFB3C9F57EEBB6941D8654BC1F4B514D6217141AEA1653C'
      schema:
        $ref: '#/components/schemas/LegacyUserId'
  requestBodies:
    query:
      required: true
      content:
        plain/text:
          schema:
            $ref: '#/components/schemas/Query'

  schemas:
    Query:
      description: 'A search string.'
      type: string
    Searches:
      type: array
      items:
        $ref: '#/components/schemas/SearchInformation'
    SearchResult:
      type: object
      additionalProperties: false
      required:
        - materials
      properties:
        materials:
          $ref: '#/components/schemas/Material'
    SearchQuery:
      type: string
    SearchInformation:
      description: 'Information about search'
      type: object
      additionalProperties:
        false
      properties:
        search:
          $ref: '#/components/schemas/SearchQuery'
        new_count:
          type: integer
    Material:
      description: 'A material'
      type: object
      required:
        - pid
      additionalProperties: true
      properties:
        pid:
          type: string
    LegacyUserId:
      description: 'Legacy user identifier.'
      type: string
      example: '29A10F616FE6CA5C6E06EBF507A9FDC5BB89F8EBCF65726BEAC61C646854E83856D3B1D46BE4696EDCFB3C9F57EEBB6941D8654BC1F4B514D6217141AEA1653C'
