# Default values for follow-searches-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: "prod"

ingress:
  enabled: true
  enableTLS: true
  cert: "letsencrypt"
  path: "/"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuTargetAverageUtilization: 70
  memoryTargetAverageUtilization: 80

app:
  image:
    version: "latest"
    imagePullPolicy: "IfNotPresent"
  db:
    host: 'k8s-ddf-prod.mariadb.database.azure.com'
    port: '3306'
    database: 'follow-searches'
    ssl: true
  adgangsplatformen:
    driver: 'production'
  log_channel: 'stderr'
  url: 'prod.followsearches.dandigbib.org'
  timezone: 'UTC'
  cacheDriver: 'file'
  queueConnection: 'sync'
  cors_allow_origin: "*"
  php:
    memory_limit: "64M"
    max_children: "10"
    start_servers: "2"
    min_spare_servers: "1"
    max_spare_servers: "3"

nginx:
  exporter:
    image:
      version: 0.11.0

