on: push
name: Build, test and deploy
jobs:
  unit_tests:
    name: Unit tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        # We're using phpdbg, we don't need a coverage extension.
        coverage: none
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Unit tests
      run: |
        phpdbg -qrr ./vendor/bin/phpunit --coverage-clover=coverage/unit.xml
    - name: Report coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -F Unit -f coverage/unit.xml

  behaviour_tests:
    name: Behaviour tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        coverage: none
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Behaviour tests
      run: |
        phpdbg -qrr vendor/bin/behat
    - name: Behaviour test coverage
      run: |
        phpdbg -qrr vendor/bin/phpcov merge --clover=coverage/behat.xml coverage/default.cov
    - name: Report coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) -F Behaviour -f coverage/behat.xml

  specification_lint:
    name: Specification linting
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lint specification
      uses: docker://wework/speccy
      with:
        args: lint follow-searches.yaml

  specification_tests:
    name: Specification tests
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.3
        coverage: none
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install Dredd
      run: |
        npm install dredd --no-optional
    - name: Specification tests
      env:
        ADGANGSPLATFORMEN_DRIVER: testing
        APP_DEBUG: "true"
        APP_ENV: testing
        DB_CONNECTION: sqlite
        DB_DATABASE: /tmp/db.sqlite
      run: |
        node_modules/.bin/dredd --loglevel=error

  deploy:
    name: Deploy
    if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop') && !github.event.deleted
    needs:
      - unit_tests
      - behaviour_tests
      - specification_lint
      - specification_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install envoy
      run: composer global require "laravel/envoy"
    - name: Deployment to server
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        PROD: ${{ (github.ref == 'refs/heads/master') }}
      run: |
        mkdir -p ~/.ssh && echo "${SSH_KEY}" >> ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -p 222 followsearches.dandigbib.org > ~/.ssh/known_hosts
        if [ "$PROD" == "true" ]; then
          ~/.composer/vendor/bin/envoy run deploy --env=prod
        else
          ~/.composer/vendor/bin/envoy run deploy --env=stage
        fi
